dsechat/apps/accounts/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy
import views
import auth_cbv

urlpatterns = patterns('',

                       # User profile
                       url(r'^profile/$',
                           views.UserProfileView.as_view(),
                           name='profile'),

                       url(r'^update/$',
                           views.UserProfileUpdateView.as_view(),
                           name='profile_update'),

                       url(r'^study/consent/$',
                           views.UserConsentView.as_view(),
                           name='consent'),

                       # Registration urls
                       url(r'^register/$',
                           views.UserRegistrationView.as_view(),
                           name='registration_register'),
                       url(r'^register/closed/$',
                           TemplateView.as_view(template_name='registration/registration_closed.html'),
                           name='registration_disallowed'),

                       # Authentication urls
                       url(r'^login/$',
                           auth_views.login,
                           {'template_name': 'registration/login.html'},
                           name='login'),
                       url(r'^logout/$',
                           views.LogoutView.as_view(),
                           name='logout'),
                       url(r'^password/change/$',
                           views.PasswordChangeView.as_view(),
                           name='password_change'),

                       url(r'^password/reset/$',
                           views.PasswordResetView.as_view(),
                           name='password_reset'),
                       url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                           views.password_reset_confirm,
                           {'post_reset_redirect': reverse_lazy('accounts:login')},
                           name='password_reset_confirm'),
)

dsechat/apps/web/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'dsechat.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^$', views.HomeView.as_view(), name="home"),
                       url(r'^setup/$', views.SetupView.as_view(), name="setup"),
                       url(r'^chat/$', views.ChatView.as_view(), name="chat"),
                       url(r'^research/$', views.ResearchView.as_view(), name="research"),
                       url(r'^contact/$', views.ContactView.as_view(), name='contact'),
                       url(r'^study/info/$', views.ConsentInfoView.as_view(), name='consent_info'),
                       url(r'^setup/pidgin/$',
                           views.SetupView.as_view(template_name="web/setup/pidgin.html"),
                           name="setup_pidgin"),
                       url(r'^setup/adium/$',
                           views.SetupView.as_view(template_name="web/setup/adium.html"),
                           name="setup_adium"),
)

dsechat/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dsechat.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('dsechat.apps.web.urls', namespace='web')),
    url(r'^accounts/', include('dsechat.apps.accounts.urls', namespace='accounts')),

)

dsechat/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# class Participant(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL)
#     over18 = models.BooleanField()
#     gives_consent = models.BooleanField()

class User(AbstractUser):
    over18 = models.BooleanField(default=False)
    gives_consent = models.BooleanField(default=False)

dsechat/apps/accounts/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from registration.models import UserModel
from models import User as AccountsUser


class UserRegistrationForm(forms.Form):
    """
    Form for registering a new user account.

    Validates that the requested username is not already in use, and
    requires the password to be entered twice to catch typos.

    Subclasses should feel free to add any additional validation they
    need, but should avoid defining a ``save()`` method -- the actual
    saving of collected user data is delegated to the active
    registration backend.
    """
    required_css_class = 'required'

    username = forms.RegexField(regex=r'^[\w.@+-]+$',
                                max_length=30,
                                label=_("Create a username"),
                                error_messages={'invalid': _(
                                    "Your username may contain only letters, numbers and @/./+/-/_ characters.")})
    email = forms.EmailField(label=_("Your email address"))

    first_name = forms.CharField(label=_("First Name"))
    last_name = forms.CharField(label=_("Last Name"))

    password1 = forms.CharField(widget=forms.PasswordInput,
                                label=_("Create a password"))
    password2 = forms.CharField(widget=forms.PasswordInput,
                                label=_("Your password again"))

    def clean_username(self):
        """
        Validate that the username is alphanumeric and is not already
        in use.

        """
        existing = UserModel().objects.filter(username__iexact=self.cleaned_data['username'])
        if existing.exists():
            raise forms.ValidationError(_("A user with that username already exists."))
        else:
            return self.cleaned_data['username']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and UserModel().objects.filter(email__iexact=email).exists():
            raise forms.ValidationError(_('A user with that email address already exists.'))
        else:
            return email

    def clean(self):
        """
        Verifiy that the values entered into the two password fields
        match. Note that an error here will end up in
        ``non_field_errors()`` because it doesn't apply to a single
        field.

        """
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields didn't match."))
        return self.cleaned_data


class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserModel()
        fields = ['email', 'first_name', 'last_name']

    required_css_class = 'required'

    email = forms.EmailField(label=_("Your email address"))

    first_name = forms.CharField(label=_("First Name"))
    last_name = forms.CharField(label=_("Last Name"))

    def clean_email(self):
        email = self.cleaned_data.get('email')
        # You cannot change your email to another user's email
        if email and UserModel().objects.filter(email__iexact=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError(_('A user with that email address already exists.'))
        else:
            return email


class ConsentForm(forms.ModelForm):
    class Meta:
        model = AccountsUser
        fields = ['gives_consent', 'over18']

    required_css_class = 'required'

    gives_consent = forms.BooleanField(label=_("I agree to participate in the research"),
                                       required=False)

    over18 = forms.BooleanField(label=_("I am 18 years of age or older"),
                                required=False)

    def clean(self):
        over18 = self.cleaned_data.get('over18')
        gives_consent = self.cleaned_data.get('gives_consent')
        if gives_consent and not over18:
            raise forms.ValidationError(_('You must be at least 18 years old to participate in the research.'))
        return self.cleaned_data

dsechat/apps/accounts/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.tokens import default_token_generator
from django.http import HttpResponseRedirect
from django.utils.translation import ugettext as _
from django.template.response import TemplateResponse
from django.views.decorators.cache import never_cache
from django.core.urlresolvers import reverse_lazy, reverse
from django.shortcuts import resolve_url
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.auth import authenticate, login
from django.views import generic
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.forms import SetPasswordForm
from django.utils.http import urlsafe_base64_decode
from registration.models import UserModel
from registration import signals
from registration.backends.simple.views import RegistrationView as SimpleRegistrationView
from django.conf import settings

from forms import UserRegistrationForm, UserProfileUpdateForm, ConsentForm
from models import User as AccountsUser
import auth_cbv


class UserRegistrationView(SimpleRegistrationView):
    form_class = UserRegistrationForm

    def register(self, request, **cleaned_data):
        username, email, password = cleaned_data['username'], cleaned_data['email'], cleaned_data['password1']
        first_name, last_name = cleaned_data['first_name'], cleaned_data['last_name']

        UserModel().objects.create_user(username, email, password,
                                        first_name=first_name, last_name=last_name)

        new_user = authenticate(username=username, password=password)
        login(request, new_user)
        signals.user_registered.send(sender=self.__class__,
                                     user=new_user,
                                     request=request)
        return new_user

    def get_success_url(self, request, user):
        return ('accounts:consent', (), {})


class UserProfileView(generic.DetailView):
    model = get_user_model()
    template_name = 'accounts/profile.html'

    def get_object(self, queryset=None):
        return self.request.user

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserProfileView, self).dispatch(*args, **kwargs)


class UserProfileUpdateView(generic.UpdateView):
    model = UserModel()
    template_name = 'accounts/profile_update.html'
    form_class = UserProfileUpdateForm
    success_url = reverse_lazy('accounts:profile')

    def get_object(self, queryset=None):
        return self.request.user

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserProfileUpdateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        result = super(UserProfileUpdateView, self).form_valid(form)
        messages.success(self.request, "Your profile has been updated.")
        return result


class UserConsentView(generic.UpdateView):
    model = AccountsUser
    template_name = 'accounts/consent_form.html'
    form_class = ConsentForm
    success_url = reverse_lazy('accounts:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get(self, request, *args, **kwargs):
        # you can't use this form if you've already consented
        if self.request.user and \
                self.request.user.is_authenticated() and \
                self.request.user.gives_consent:
            return redirect('web:consent_info')
        return super(UserConsentView, self).get(request, *args, **kwargs)


    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserConsentView, self).dispatch(*args, **kwargs)


class PasswordChangeView(auth_cbv.PasswordChangeView):
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        result = super(PasswordChangeView, self).form_valid(form)
        update_session_auth_hash(self.request, form.user)
        messages.success(self.request, "Your password has been changed.")
        return result


class LogoutView(auth_cbv.LogoutView):
    def get_success_url(self):
        return reverse('accounts:login')

    def get(self, request, *args, **kwargs):
        messages.success(self.request, "You have been signed out.")
        return super(LogoutView, self).get(request, *args, **kwargs)


class PasswordResetView(auth_cbv.PasswordResetView):
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        response = super(PasswordResetView, self).form_valid(form)
        messages.success(self.request, "An email has been sent with a link to choose a new password.")
        return response


# Doesn't need csrf_protect since no-one can guess the URL
@sensitive_post_parameters()
@never_cache
def password_reset_confirm(request, uidb64=None, token=None,
                           template_name='registration/password_reset_confirm.html',
                           token_generator=default_token_generator,
                           set_password_form=SetPasswordForm,
                           post_reset_redirect=None,
                           current_app=None, extra_context=None):
    """
    View that checks the hash in a password reset link and presents a
    form for entering a new password.
    """
    UserModel = get_user_model()
    assert uidb64 is not None and token is not None  # checked by URLconf
    if post_reset_redirect is None:
        post_reset_redirect = reverse('password_reset_complete')
    else:
        post_reset_redirect = resolve_url(post_reset_redirect)
    try:
        uid = urlsafe_base64_decode(uidb64)
        user = UserModel._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, UserModel.DoesNotExist):
        user = None

    if user is not None and token_generator.check_token(user, token):
        validlink = True
        title = _('Enter new password')
        if request.method == 'POST':
            form = set_password_form(user, request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Your password has been changed. Please log in.")
                return HttpResponseRedirect(post_reset_redirect)
        else:
            form = set_password_form(user)
    else:
        validlink = False
        form = None
        title = _('Password reset unsuccessful')
    context = {
        'form': form,
        'title': title,
        'validlink': validlink,
    }
    if extra_context is not None:
        context.update(extra_context)
    return TemplateResponse(request, template_name, context,
                            current_app=current_app)

dsechat/apps/web/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.

class HomeView(TemplateView):
    template_name = "web/home.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['contact_email'] = settings.SITE_CONTACT_EMAIL
        return context


class SetupView(TemplateView):
    template_name = "web/setup.html"

    def get_context_data(self, **kwargs):
        context = super(SetupView, self).get_context_data(**kwargs)
        context['xmpp_server'] = settings.XMPP_SERVER
        context['xmpp_server_port'] = settings.XMPP_SERVER_PORT
        context['xmpp_muc_room'] = settings.XMPP_MUC_ROOM
        context['xmpp_muc_server'] = settings.XMPP_MUC_SERVER
        return context


class RegisterView(TemplateView):
    template_name = "web/signup.html"


class ChatView(TemplateView):
    template_name = "web/chat.html"

    def get_context_data(self, **kwargs):
        context = super(ChatView, self).get_context_data(**kwargs)
        context['xmpp_server'] = settings.XMPP_SERVER
        context['xmpp_bosh_url'] = settings.XMPP_BOSH_URL
        context['session_cookie_name'] = settings.SESSION_COOKIE_NAME
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ChatView, self).dispatch(*args, **kwargs)

class ConsentInfoView(TemplateView):
    template_name = 'web/consent_page.html'


class ContactView(TemplateView):
    template_name = "web/contact.html"

    def get_context_data(self, **kwargs):
        context = super(ContactView, self).get_context_data(**kwargs)
        context['study_contact_name'] = settings.STUDY_CONTACT_NAME
        context['study_contact_email'] = settings.STUDY_CONTACT_EMAIL
        context['site_contact_email'] = settings.SITE_CONTACT_EMAIL
        return context


class ResearchView(TemplateView):
    template_name = "web/research.html"

dsechat/templates/web/chat.html
{% extends 'base.html' %}
{% load compress staticfiles %}
{% block page_css %}
    {{ block.super }}

    {% compress css %}
        <!-- Candy CSS -->
{#        <link rel="stylesheet" type="text/css" href="{% static 'css/webchat.css' %}" />#}
        <link rel="stylesheet" type="text/css" href="{% static 'vendor/bower/candy-plugins/inline-images/candy.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'vendor/bower/candy-plugins/replies/candy.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'vendor/bower/candy-plugins/timeago/candy.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'vendor/bower/candy-plugins/typingnotifications/typingnotifications.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'candy-plugins/auto_domain/candy.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'candy-plugins/bootstrapify/candy.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/webchat.css' %}"/>
    {% endcompress %}
{% endblock %}

{% block page_js %}
    {{ block.super }}

    {% compress js %}
        <!-- Candy JS -->
        <script type="text/javascript" src="{% static 'vendor/bower/candy/libs/libs.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/bower/candy/candy.bundle.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/bower/candy-plugins/inline-images/candy.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/bower/candy-plugins/notifications/candy.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/bower/candy-plugins/replies/candy.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/bower/candy-plugins/timeago/candy.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/bower/candy-plugins/typingnotifications/typingnotifications.js' %}"></script>
        <script type="text/javascript" src="{% static 'candy-plugins/auto_domain/candy.js' %}"></script>
        <script type="text/javascript" src="{% static 'candy-plugins/bootstrapify/candy.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/bower/jquery-cookie/jquery.cookie.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/webchat.js' %}"></script>
    {% endcompress %}

    <script type="text/javascript">
        window.webchat = {
            assets: '{% static "vendor/bower/candy/res/" %}',
        {% if user.is_authenticated %}
            user: {
                username: '{{ user.username }}',
                nickname: '{{ user.first_name }} {{ user.last_name }}'.trim()
            },
        {% endif %}
            xmpp_server: '{{ xmpp_server }}',
            xmpp_bosh_url: '{{ xmpp_bosh_url }}',
            session_cookie_name: '{{ session_cookie_name }}'
        };
    </script>
{% endblock %}

{% block content %}
    <div class="webchat-wrapper">
        <div id="candy"></div>
    </div>
{% endblock %}

dsechat/templates/web/consent_page.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="container interior">
        <div class="consent-info">
            <h1 class="page-header">Collaborative Chat for Data Science</h1>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Consent Information</strong>
                </div>
                <div class="panel-body">
                    {% include 'snippets/study_information.html' %}
                </div>
                <div class="panel-footer">
                    {% if user.is_authenticated and user.gives_consent %}
                        <p>
                            You have agreed to participate in this research.
                            If you would like to withdraw from the study, please
                            <a href="{% url 'web:contact' %}">contact us</a>.
                            <br/>
                            You can still use the chat room without being in the study.
                        </p>
                    {% elif user.is_authenticated %}
                        You have not agreed to participate.
                        <a href="{% url 'accounts:consent' %}">Change my setting</a>.
                    {% else %}
                        <a href="{% url 'accounts:registration_register' %}"
                           class="btn btn-lg btn-primary">Create an account</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

dsechat/templates/web/contact.html
{% extends "base.html" %}
{% block content %}
    <div class="container interior">
        <div class="focus-form-wrapper">
            <h1 class="page-header">Contact Us</h1>

            <p class="lead">
                For questions about our research on the data science chat room,
                contact <strong>{{ study_contact_name }}</strong> at
                <a href="mailto:{{ study_contact_email }}">{{ study_contact_email }}</a>.
                <br/>
                We cannot guarantee the confidentiality of information sent by email.
            </p>

            <p class="lead">
                For all other questions, contact <a href="mailto:{{ site_contact_email }}">{{ site_contact_email }}</a>.
            </p>
        </div>
    </div>
{% endblock %}

dsechat/templates/web/home.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <div class="container interior">
            <h1>Chat with Data Scientists</h1>

            <p class="lead">
                An online community for data scientists across NYU, Berkeley, and UW.
            </p>

            <p>
                {% if not user.is_authenticated %}
                    <a class="btn btn-lg btn-action"
                       href="{% url 'accounts:registration_register' %}"
                       role="button">Create an account</a>
                {% endif %}
            </p>
        </div>
    </div>

    <div class="container interior">
        <div class="row marketing">
            <div class="col-md-6">
                <h4>Connect and Communicate</h4>

                <p>
                    The data science chat room is a social space where data scientists across
                    NYU, Berkeley, and UW can gather:
                </p>

                <ul>
                    <li>Ask questions and share advice about data science.</li>
                    <li>Get to know other data scientists.</li>
                    <li>Socialize and build a data science community.</li>
                </ul>

                <h4>It's Science!</h4>

                <p>
                    Group chat rooms are a great way for a geographically dispersed
                    group of people to stay in touch. Since chat is less formal than email,
                    it can be fun and social. At the same time, you can use the chat room to ask
                    questions and find people who can help you solve work problems.
                </p>

                <p><a href="{% url 'web:research' %}">Read more about why chat is great for online collaboration</a>.
                </p>

            </div>

            <div class="col-md-6">
                <h4>Get started</h4>

                <p>
                    Once you <a href="{% url 'accounts:registration_register' %}">create an account</a>,
                    you can get started quickly using the <a href="{% url 'web:chat' %}">web-based client</a>, right in
                    your
                    browser. You can also <a href="{% url 'web:setup' %}">connect to the chat room</a> using any chat
                    client
                    that supports XMPP.
                </p>

                <h4>About us</h4>

                <p>
                    The data science chat room is based at the University of Washington.
                    It is operated by Professor Cecilia Aragon, Michael Brooks, and Brittany Fiore-Silfvast.
                </p>

                <p>
                    This project is part of a cross-campus collaborative data science effort
                    supported by the Gordon and Betty Moore Foundation and the Alfred P. Sloan Foundation.
                    <a href="http://escience.washington.edu/blog/introducing-data-science-environment"
                       target="_blank">Read more about this initiative.</a>
                </p>

                <p>
                    For questions about the data science chat room, <a href="{% url 'web:contact' %}">contact us</a>.
                    Learn more about <a href="http://data.uw.edu/" target="_blank">Data Science at UW</a>.
                </p>

            </div>
        </div>
    </div>
{% endblock %}

dsechat/templates/web/setup.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="container interior">
        <h1 class="page-header">Chat Client Configuration</h1>

        <p class="lead">You can connect to the data science chat room using any client that supports XMPP.</p>

        <p>
            The data science chat room uses
            <a href="https://en.wikipedia.org/wiki/XMPP" target="_blank">XMPP/Jabber</a>.
            XMPP is an open chat protocol that is supported by a wide range of client programs and services.
        </p>

        <p>
            We provide instructions for connecting to the data science chat room with Pidgin and Adium, two popular
            open-source chat programs. However, the setup should be similar if you want to connect with
            <a href="http://xmpp.org/xmpp-software/clients/" target="_blank">another XMPP client</a>.
        </p>

        <p><strong>Note: Before you can connect, you must have a
            <a href="{% url 'accounts:registration_register' %}">valid username and password</a>.</strong></p>

        <div class="client-options row">
            <div class="col-sm-2">
                <p class="lead">Client instructions:</p>
            </div>
            <div class="col-sm-9">
                <a href="{% url 'web:setup_pidgin' %}" class="btn btn-lg btn-default">
                    Pidgin
                    <p class="small text-muted">Windows and Linux</p>
                </a>
                <a href="{% url 'web:setup_adium' %}" class="btn btn-lg btn-default">
                    Adium
                    <p class="small text-muted">Mac OS X</p>
                </a>
                <a class="btn btn-lg btn-default disabled">
                    Mobile
                    <p class="small text-muted">Coming soon!</p>
                </a>
            </div>
        </div>

        <div class="other-client-instructions">
            <a id="other" class="anchor"></a>

            <div class="media">
                <a class="pull-left" href="http://xmpp.org/xmpp-software/clients/">
                    <img class="media-object client-logo" src="{% static 'img/xmpp.logo.png' %}" alt="XMPP logo">
                </a>

                <div class="media-body">
                    <h2 class="media-heading">Other XMPP clients</h2>

                    <p>There are many XMPP clients out there. The XMPP Standards Foundation
                        <a href="http://xmpp.org/xmpp-software/clients/" target="_blank">maintains a list</a>.</p>

                    <p>The details below should be sufficient for connecting most clients to the data science chat
                        room.</p>

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Connection Details
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <label class="col-xs-3">XMPP Domain:</label>

                                <div class="col-xs-9"><code>{{ xmpp_server }}</code></div>
                            </div>

                            <div class="row">
                                <label class="col-xs-3">Port number:</label>

                                <div class="col-xs-9">
                                    <code>{{ xmpp_server_port }}</code>
                                    {% if xmpp_server_port == 5222 %}
                                        (Default)
                                    {% endif %}
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-xs-3">Conference Domain:</label>

                                <div class="col-xs-9"><code>{{ xmpp_muc_server }}</code></div>
                            </div>

                            <div class="row">
                                <label class="col-xs-3">Room Name:</label>

                                <div class="col-xs-9"><code>{{ xmpp_muc_room }}</code></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}