dsechat/apps/accounts/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy
import views
import auth_cbv

urlpatterns = patterns('',

                       # User profile
                       url(r'^profile/$',
                           views.UserProfileView.as_view(),
                           name='profile'),

                       url(r'^update/$',
                           views.UserProfileUpdateView.as_view(),
                           name='profile_update'),

                       url(r'^study/consent/$',
                           views.UserConsentView.as_view(),
                           name='consent'),

                       # Registration urls
                       url(r'^register/$',
                           views.UserRegistrationView.as_view(),
                           name='registration_register'),
                       url(r'^register/closed/$',
                           TemplateView.as_view(template_name='registration/registration_closed.html'),
                           name='registration_disallowed'),

                       # Authentication urls
                       url(r'^login/$',
                           auth_views.login,
                           {'template_name': 'registration/login.html'},
                           name='login'),
                       url(r'^logout/$',
                           views.LogoutView.as_view(),
                           name='logout'),
                       url(r'^password/change/$',
                           views.PasswordChangeView.as_view(),
                           name='password_change'),

                       url(r'^password/reset/$',
                           views.PasswordResetView.as_view(),
                           name='password_reset'),
                       url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                           views.password_reset_confirm,
                           {'post_reset_redirect': reverse_lazy('accounts:login')},
                           name='password_reset_confirm'),
)

dsechat/apps/web/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'dsechat.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^$', views.HomeView.as_view(), name="home"),
                       url(r'^setup/$', views.SetupView.as_view(), name="setup"),
                       url(r'^chat/$', views.ChatView.as_view(), name="chat"),
                       url(r'^research/$', views.ResearchView.as_view(), name="research"),
                       url(r'^contact/$', views.ContactView.as_view(), name='contact'),
                       url(r'^study/info/$', views.ConsentInfoView.as_view(), name='consent_info'),
                       url(r'^setup/pidgin/$',
                           views.SetupView.as_view(template_name="web/setup/pidgin.html"),
                           name="setup_pidgin"),
                       url(r'^setup/adium/$',
                           views.SetupView.as_view(template_name="web/setup/adium.html"),
                           name="setup_adium"),
)

dsechat/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dsechat.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('dsechat.apps.web.urls', namespace='web')),
    url(r'^accounts/', include('dsechat.apps.accounts.urls', namespace='accounts')),

)

dsechat/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# class Participant(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL)
#     over18 = models.BooleanField()
#     gives_consent = models.BooleanField()

class User(AbstractUser):
    over18 = models.BooleanField(default=False)
    gives_consent = models.BooleanField(default=False)

dsechat/apps/accounts/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from registration.models import UserModel
from models import User as AccountsUser


class UserRegistrationForm(forms.Form):
    """
    Form for registering a new user account.

    Validates that the requested username is not already in use, and
    requires the password to be entered twice to catch typos.

    Subclasses should feel free to add any additional validation they
    need, but should avoid defining a ``save()`` method -- the actual
    saving of collected user data is delegated to the active
    registration backend.
    """
    required_css_class = 'required'

    username = forms.RegexField(regex=r'^[\w.@+-]+$',
                                max_length=30,
                                label=_("Create a username"),
                                error_messages={'invalid': _(
                                    "Your username may contain only letters, numbers and @/./+/-/_ characters.")})
    email = forms.EmailField(label=_("Your email address"))

    first_name = forms.CharField(label=_("First Name"))
    last_name = forms.CharField(label=_("Last Name"))

    password1 = forms.CharField(widget=forms.PasswordInput,
                                label=_("Create a password"))
    password2 = forms.CharField(widget=forms.PasswordInput,
                                label=_("Your password again"))

    def clean_username(self):
        """
        Validate that the username is alphanumeric and is not already
        in use.

        """
        existing = UserModel().objects.filter(username__iexact=self.cleaned_data['username'])
        if existing.exists():
            raise forms.ValidationError(_("A user with that username already exists."))
        else:
            return self.cleaned_data['username']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and UserModel().objects.filter(email__iexact=email).exists():
            raise forms.ValidationError(_('A user with that email address already exists.'))
        else:
            return email

    def clean(self):
        """
        Verifiy that the values entered into the two password fields
        match. Note that an error here will end up in
        ``non_field_errors()`` because it doesn't apply to a single
        field.

        """
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields didn't match."))
        return self.cleaned_data


class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserModel()
        fields = ['email', 'first_name', 'last_name']

    required_css_class = 'required'

    email = forms.EmailField(label=_("Your email address"))

    first_name = forms.CharField(label=_("First Name"))
    last_name = forms.CharField(label=_("Last Name"))

    def clean_email(self):
        email = self.cleaned_data.get('email')
        # You cannot change your email to another user's email
        if email and UserModel().objects.filter(email__iexact=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError(_('A user with that email address already exists.'))
        else:
            return email


class ConsentForm(forms.ModelForm):
    class Meta:
        model = AccountsUser
        fields = ['gives_consent', 'over18']

    required_css_class = 'required'

    gives_consent = forms.BooleanField(label=_("I agree to participate in the research"),
                                       required=False)

    over18 = forms.BooleanField(label=_("I am 18 years of age or older"),
                                required=False)

    def clean(self):
        over18 = self.cleaned_data.get('over18')
        gives_consent = self.cleaned_data.get('gives_consent')
        if gives_consent and not over18:
            raise forms.ValidationError(_('You must be at least 18 years old to participate in the research.'))
        return self.cleaned_data

dsechat/apps/accounts/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.tokens import default_token_generator
from django.http import HttpResponseRedirect
from django.utils.translation import ugettext as _
from django.template.response import TemplateResponse
from django.views.decorators.cache import never_cache
from django.core.urlresolvers import reverse_lazy, reverse
from django.shortcuts import resolve_url
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.auth import authenticate, login
from django.views import generic
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.forms import SetPasswordForm
from django.utils.http import urlsafe_base64_decode
from registration.models import UserModel
from registration import signals
from registration.backends.simple.views import RegistrationView as SimpleRegistrationView
from django.conf import settings

from forms import UserRegistrationForm, UserProfileUpdateForm, ConsentForm
from models import User as AccountsUser
import auth_cbv


class UserRegistrationView(SimpleRegistrationView):
    form_class = UserRegistrationForm

    def register(self, request, **cleaned_data):
        username, email, password = cleaned_data['username'], cleaned_data['email'], cleaned_data['password1']
        first_name, last_name = cleaned_data['first_name'], cleaned_data['last_name']

        UserModel().objects.create_user(username, email, password,
                                        first_name=first_name, last_name=last_name)

        new_user = authenticate(username=username, password=password)
        login(request, new_user)
        signals.user_registered.send(sender=self.__class__,
                                     user=new_user,
                                     request=request)
        return new_user

    def get_success_url(self, request, user):
        return ('accounts:consent', (), {})


class UserProfileView(generic.DetailView):
    model = get_user_model()
    template_name = 'accounts/profile.html'

    def get_object(self, queryset=None):
        return self.request.user

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserProfileView, self).dispatch(*args, **kwargs)


class UserProfileUpdateView(generic.UpdateView):
    model = UserModel()
    template_name = 'accounts/profile_update.html'
    form_class = UserProfileUpdateForm
    success_url = reverse_lazy('accounts:profile')

    def get_object(self, queryset=None):
        return self.request.user

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserProfileUpdateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        result = super(UserProfileUpdateView, self).form_valid(form)
        messages.success(self.request, "Your profile has been updated.")
        return result


class UserConsentView(generic.UpdateView):
    model = AccountsUser
    template_name = 'accounts/consent_form.html'
    form_class = ConsentForm
    success_url = reverse_lazy('accounts:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get(self, request, *args, **kwargs):
        # you can't use this form if you've already consented
        if self.request.user and \
                self.request.user.is_authenticated() and \
                self.request.user.gives_consent:
            return redirect('web:consent_info')
        return super(UserConsentView, self).get(request, *args, **kwargs)


    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserConsentView, self).dispatch(*args, **kwargs)


class PasswordChangeView(auth_cbv.PasswordChangeView):
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        result = super(PasswordChangeView, self).form_valid(form)
        update_session_auth_hash(self.request, form.user)
        messages.success(self.request, "Your password has been changed.")
        return result


class LogoutView(auth_cbv.LogoutView):
    def get_success_url(self):
        return reverse('accounts:login')

    def get(self, request, *args, **kwargs):
        messages.success(self.request, "You have been signed out.")
        return super(LogoutView, self).get(request, *args, **kwargs)


class PasswordResetView(auth_cbv.PasswordResetView):
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        response = super(PasswordResetView, self).form_valid(form)
        messages.success(self.request, "An email has been sent with a link to choose a new password.")
        return response


# Doesn't need csrf_protect since no-one can guess the URL
@sensitive_post_parameters()
@never_cache
def password_reset_confirm(request, uidb64=None, token=None,
                           template_name='registration/password_reset_confirm.html',
                           token_generator=default_token_generator,
                           set_password_form=SetPasswordForm,
                           post_reset_redirect=None,
                           current_app=None, extra_context=None):
    """
    View that checks the hash in a password reset link and presents a
    form for entering a new password.
    """
    UserModel = get_user_model()
    assert uidb64 is not None and token is not None  # checked by URLconf
    if post_reset_redirect is None:
        post_reset_redirect = reverse('password_reset_complete')
    else:
        post_reset_redirect = resolve_url(post_reset_redirect)
    try:
        uid = urlsafe_base64_decode(uidb64)
        user = UserModel._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, UserModel.DoesNotExist):
        user = None

    if user is not None and token_generator.check_token(user, token):
        validlink = True
        title = _('Enter new password')
        if request.method == 'POST':
            form = set_password_form(user, request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Your password has been changed. Please log in.")
                return HttpResponseRedirect(post_reset_redirect)
        else:
            form = set_password_form(user)
    else:
        validlink = False
        form = None
        title = _('Password reset unsuccessful')
    context = {
        'form': form,
        'title': title,
        'validlink': validlink,
    }
    if extra_context is not None:
        context.update(extra_context)
    return TemplateResponse(request, template_name, context,
                            current_app=current_app)

dsechat/apps/web/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.

class HomeView(TemplateView):
    template_name = "web/home.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['contact_email'] = settings.SITE_CONTACT_EMAIL
        return context


class SetupView(TemplateView):
    template_name = "web/setup.html"

    def get_context_data(self, **kwargs):
        context = super(SetupView, self).get_context_data(**kwargs)
        context['xmpp_server'] = settings.XMPP_SERVER
        context['xmpp_server_port'] = settings.XMPP_SERVER_PORT
        context['xmpp_muc_room'] = settings.XMPP_MUC_ROOM
        context['xmpp_muc_server'] = settings.XMPP_MUC_SERVER
        return context


class RegisterView(TemplateView):
    template_name = "web/signup.html"


class ChatView(TemplateView):
    template_name = "web/chat.html"

    def get_context_data(self, **kwargs):
        context = super(ChatView, self).get_context_data(**kwargs)
        context['xmpp_server'] = settings.XMPP_SERVER
        context['xmpp_bosh_url'] = settings.XMPP_BOSH_URL
        context['session_cookie_name'] = settings.SESSION_COOKIE_NAME
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ChatView, self).dispatch(*args, **kwargs)

class ConsentInfoView(TemplateView):
    template_name = 'web/consent_page.html'


class ContactView(TemplateView):
    template_name = "web/contact.html"

    def get_context_data(self, **kwargs):
        context = super(ContactView, self).get_context_data(**kwargs)
        context['study_contact_name'] = settings.STUDY_CONTACT_NAME
        context['study_contact_email'] = settings.STUDY_CONTACT_EMAIL
        context['site_contact_email'] = settings.SITE_CONTACT_EMAIL
        return context


class ResearchView(TemplateView):
    template_name = "web/research.html"

dsechat/templates/base.html
{% load compress static lineage bootstrap3 %}
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Data Science Chat{% endblock %}</title>
    <meta name="description" content="A chat room for data scientists">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <!-- Load Source Sans Pro font -->
    <link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic' rel='stylesheet' type='text/css'/>

    {% block page_css %}
        {% compress css %}
            <!-- Vendor css -->
            <link rel="stylesheet" href="{% static 'css/bootstrap_theme.less' %}" type="text/less"/>
            <link rel="stylesheet" href="{% static 'vendor/bower/ie10-viewport-fix/ie10-viewport-fix.css' %}"/>
        {% endcompress %}

        {% compress css %}
            <!-- Site CSS -->
            <link rel="stylesheet" href="{% static 'css/forms.css' %}"/>
            <link rel="stylesheet" href="{% static 'css/user_profile.css' %}"/>
            <link rel="stylesheet" href="{% static 'css/home_page.less' %}" type="text/less"/>
            <link rel="stylesheet" href="{% static 'css/research_page.css' %}"/>
            <link rel="stylesheet" href="{% static 'css/setup_page.css' %}"/>
            <link rel="stylesheet" href="{% static 'css/consent_page.css' %}"/>
        {% endcompress %}

    {% endblock %}

</head>
<body>

<!--[if lt IE 10]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> to improve your experience.</p>
<![endif]-->

<div class="container">

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'web:home' %}">Data Science Chat</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="{% ancestor 'web:setup' %}"><a href="{% url 'web:setup' %}">Client Setup</a></li>
                    <li class="{% ancestor 'web:chat' %}"><a href="{% url 'web:chat' %}">
                        Web Chat
                        <span class="label label-default">BETA</span>
                    </a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li class="{% ancestor 'accounts:profile' %}">
                            <a href="{% url 'accounts:profile' %}"
                               title="View my profile">Hello, {{ user.first_name }}</a>
                        </li>
                        <li><a href="{% url 'accounts:logout' %}">Sign out</a></li>
                    {% else %}
                        <li class="{% ancestor 'accounts:login' %}">
                            <a href="{% url 'accounts:login' %}">Sign in</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>

    <div class="container interior">
        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}
    </div>

    <div class="content">
        {% block content %}{% endblock %}
    </div>
</div>

<div class="footer">
    <div class="container">
        <p class="navbar-text">&copy; University of Washington 2014</p>
        <ul class="footer-nav pull-right">
            <li><a href="//www.washington.edu/online/privacy" target="_blank">Privacy</a></li>
            <li><a href="//www.washington.edu/online/terms" target="_blank">Terms</a></li>
        </ul>
    </div>
</div>

{% block page_js %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

    {% compress js %}
        <!-- Vendor JS -->
        <script src="{% static 'vendor/bower/bootstrap/dist/js/bootstrap.js' %}"></script>
        <script src="{% static 'vendor/bower/wp8-ie10-fix/wp8-ie10-fix.js' %}"></script>
    {% endcompress %}
{% endblock %}

{% if ga_tracking_id %}
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '{{ ga_tracking_id }}', 'auto');
    ga('send', 'pageview');

</script>
{% endif %}

</body>
</html>